# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-12-11 13:30
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diet_planapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fill_formmodel',
            name='user',
            field=models.OneToOneField(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
