# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-12-11 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_planapp', '0004_auto_20211211_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fill_formmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
